{% set version = "0.2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-fateid
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/FateID_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/FateID/FateID_{{ version }}.tar.gz
  sha256: 9536bfd13051bb1fed0865a2cfca727fe77f1d95a1ae51a866b3d6892156fb69

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-rtsne
    - r-lle
    - r-locfit
    - r-matrixstats
    - r-pheatmap
    - r-princurve
    - r-randomforest
    - r-som
    - r-umap
  run:
    - r-base
    - r-rcolorbrewer
    - r-rtsne
    - r-lle
    - r-locfit
    - r-matrixstats
    - r-pheatmap
    - r-princurve
    - r-randomforest
    - r-som
    - r-umap

test:
  commands:
    - $R -e "library('FateID')"           # [not win]
    - "\"%R%\" -e \"library('FateID')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=FateID
  license: GPL-3.0-only
  summary: Application of 'FateID' allows computation and visualization of cell fate bias for multi-lineage single cell transcriptome data. Herman, J.S., Sagar, Grün D. (2018) <DOI:10.1038/nmeth.4662>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: FateID
# Title: Quantification of Fate Bias in Multipotent Progenitors
# Version: 0.1.9
# Date: 2019-09-21
# Author: Dominic Grun <dominic.gruen@gmail.com>
# Maintainer: Dominic Grun <dominic.gruen@gmail.com>
# Description: Application of 'FateID' allows computation and visualization of cell fate bias for multi-lineage single cell transcriptome data. Herman, J.S., Sagar, Grun D. (2018) <DOI:10.1038/nmeth.4662>.
# Depends: R (>= 3.4)
# Imports: graphics, grDevices, lle, locfit, pheatmap, princurve, randomForest, RColorBrewer, Rtsne, som, stats, umap, utils
# Suggests: DESeq2, destiny, knitr, rmarkdown
# VignetteBuilder: knitr
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2019-09-21 19:06:06 UTC; d.grun
# Repository: CRAN
# Date/Publication: 2019-09-21 20:20:06 UTC
