travis:
  secure:
    BINSTAR_TOKEN: oLiI2aZOwZzBVPq0fj9vKZUqFHy06vpZ1yAnYvMKzoaAZ7KWdn+9cS47jzrcPGDYTGwk7fj7MAoKMzU/N30nHUdAJLyiNlj6GfNne7rVUDm55UTI7PZ6jRC8QZqpGxAnKy04Yp0bABhzMFzdWBD4n7CxDjGlpi8kyZ+HK2HGy4MlH/jCJuWTw1bNLYQghZsjIWSRaY/14klzSQnJtFX1YOSWuO33WNKYsq0vpApzRge6uMORq3Zw7fnGn3YWo9AdOqouttbn97iyQ4iIrAoE0caf6Pmwv/8KE6wpdyC3IQuqoCeOx+5bJpeIXk6chaw1Hc0O32BC4FW792fQmlS9N+gK2FQ+0p6n7drGGrf0ygdRpu6AFRHSVpbGwqZx9FoezVJUOmKGki56SPufa+UmalgTIArz/GIZ0EYvAla/o4o7BGZxr7lUAqPScNOMAMedoOaFlSksKUqB4jngD6EM642ruzx9/ozxpdPfmwMKmorXoxLD6bSpAJ2c75A3F10LoPJvV34VrOF1qSAHJ930A9UNssgg498E9bPW862I1Xa9Ey6WgjtxZdoYnNUNXilNpYROx0lQLgPqMUFmek/9Es/45cdcLvd+TsewQ9/Txtaxg2CjBUYDFlW1BZaMuhBaYAYVZ5PeRau26BaOAaYYlRbyWJR4Kt7DvIg0QO2evpU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
